### ISSUE TITLE
Alignment Error

### ISSUE THREAD

**Issue by gmltmd789** [vadimkantorov/ctc#3]
First, thank you for your implementation of CTC, and sorry for my pool English.

When I run your example.py with pytorch 1.7.1 to extract alignment images like in repo's readme, I get an error as below;

![image](https://user-images.githubusercontent.com/49265950/124149205-54272580-dacb-11eb-99ad-7e646afac3c0.png)
![image](https://user-images.githubusercontent.com/49265950/124149237-59847000-dacb-11eb-8e65-65483a9943fb.png)

I don't know how to solve it. If you don't mind, can you tell me how to extract alignment path?

**Comment by vadimkantorov** [comment]
Thanks for reporting! I'll take a look later this week. In the meanwhile, you may try to find an earlier commit in history that works

**Comment by blankspark** [comment]
I wonder if you have solved this problem. I met the same quetion .  Looking forward to your reply.

**Comment by vadimkantorov** [comment]
I fixed the alignment problem. Thanks!
